// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Types {
  name: string;
  category: string;
  price: number;
  currency: string;
  image: { [key: string]: string };
  bestseller: boolean;
  featured: boolean;
  details: Details;
}

export interface Details {
  dimensions: Dimmentions;
  size: number;
  description: string;
}

export interface Dimmentions {
  width: number;
  height: number;
}
